# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY . .
RUN dotnet restore UrlShortener.API/UrlShortener.API.csproj
RUN dotnet publish UrlShortener.API/UrlShortener.API.csproj -c Release -o out

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/out .

EXPOSE 10000
ENTRYPOINT ["dotnet", "UrlShortener.API.dll"]