using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UrlShortener.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class FixPostgresIdentityColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            AddIdentityAndSyncSequence(migrationBuilder, "Users");
            AddIdentityAndSyncSequence(migrationBuilder, "Urls");
            AddIdentityAndSyncSequence(migrationBuilder, "UrlClicks");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            DropIdentityIfExists(migrationBuilder, "Users");
            DropIdentityIfExists(migrationBuilder, "Urls");
            DropIdentityIfExists(migrationBuilder, "UrlClicks");
        }

        private static void AddIdentityAndSyncSequence(MigrationBuilder migrationBuilder, string tableName)
        {
            migrationBuilder.Sql($$"""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_attribute
                        WHERE attrelid = '"{{tableName}}"'::regclass
                          AND attname = 'Id'
                          AND attidentity IN ('a', 'd')
                    ) THEN
                        ALTER TABLE public."{{tableName}}"
                        ALTER COLUMN "Id"
                        ADD GENERATED BY DEFAULT AS IDENTITY;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql($$"""
                SELECT setval(
                    pg_get_serial_sequence('public."{{tableName}}"', 'Id'),
                    COALESCE((SELECT MAX("Id") FROM public."{{tableName}}"), 0) + 1,
                    false
                );
                """);
        }

        private static void DropIdentityIfExists(MigrationBuilder migrationBuilder, string tableName)
        {
            migrationBuilder.Sql($$"""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM pg_attribute
                        WHERE attrelid = '"{{tableName}}"'::regclass
                          AND attname = 'Id'
                          AND attidentity IN ('a', 'd')
                    ) THEN
                        ALTER TABLE public."{{tableName}}"
                        ALTER COLUMN "Id"
                        DROP IDENTITY IF EXISTS;
                    END IF;
                END $$;
                """);
        }
    }
}
